---
- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow all access from vlan
  community.general.ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - "{{ vlan }}"

- name: Deny all
  community.general.ufw:
    state: enabled
    direction: incoming
    policy: deny
