---
- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow all access from private lan
  community.general.ufw:
    rule: allow
    src: "{{ private_lan }}"

- name: Deny all
  community.general.ufw:
    state: enabled
    direction: incoming
    policy: deny
