---
- name: Add docker.com GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker.com apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable

- name: Install required packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-compose-plugin
      - python3-pip
      - python3-jsondiff

- name: Make sure docker python module is installed
  ansible.builtin.pip:
    name: docker
