---
name: CI
on:  # yamllint disable-line
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: setup-python

      - uses: actions/cache@v3
        id: deps-cache
        with:
          path: |
            venv
            ~/.ansible
            ./.cache
          key: v2-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.yml') }}

      - name: Install dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          ansible-galaxy install -r requirements.yml

      - name: Load secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          ANSIBLE_VAULT_KEY: op://infra-fands/Ansible vault key/password

      - name: Restore ansible vault password
        run: echo ${{ ANSIBLE_VAULT_KEY }} > .vault-key

      - name: Run the lint
        run: |
          . venv/bin/activate
          make lint

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - uses: actions/cache/restore@v3
        id: deps-cache
        with:
          path: |
            venv
            ~/.ansible
            ./.cache
          key: v2-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.yml') }}
          fail-on-cache-miss: true

      - name: Load secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          ANSIBLE_VAULT_KEY: op://infra-fands/Ansible vault key/password
          DEPLOY_KEY: op://infra-fands/Infra deploy SSH Key/private key?ssh-format=openssh

      - name: Restore ansible vault password
        run: echo ${{ ANSIBLE_VAULT_KEY }} > .vault-key

      - name: Install ssh keys
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ DEPLOY_KEY }}

      - name: Run the playbook
        run: |
          . venv/bin/activate
          ansible-playbook site.yml --inventory hosts.yml --user infra --become
